Feat/game matching  (#109)
404-DriverNotFound/backend-b pull request #110
Opened 2021-09-30 10:13 UTC by Jack-R-lantern

## 기능에 대한 설명
매칭 타입과 모드에 따라 매칭이 일어날수 있는 로직

## 테스트 (Optional)
1. 두 사람이 다른 게임 모드를 선택했을때 매칭이 안일어나는지 확인 (O)
2. 두 사람이 같은 게임 모드를  선택했을때 매칭이 일어나는지 확인 (O)
3. DB에 해당하는 타입과 모드로 매칭기록이 저장되는지 확인 (O)

## ISSUE
close #109

2021-09-30 11:47 UTC, Jack-R-lantern commented
기존 로직에서 매칭 취소시 큐에서 사라지지 않는 문제가 있어서 수정했습니다.
https://github.com/404-DriverNotFound/backend-b/pull/110/commits/c2073c8c9fac3f9f0248dbfb4c42e674b635301e

2021-09-30 15:04 UTC, ykoh42 requested changes
dto 부분 작동하지 않는 부분에 대한 리뷰 남겼습니다.

2021-09-30 15:04 UTC, ykoh42 commented on src/events/events.gateway.ts
> +    @MessageBody() { type, mode }: OnMatchTypeModeDto,
현재 방식대로는 값이 넘어오지 않습니다.

아래와 같이 수정해야 값이 넘어와용

```suggestion
    @MessageBody() [ type, mode ]: string[],
```

2021-09-30 15:04 UTC, ykoh42 commented on src/events/events.gateway.ts
> +    @MessageBody() { type, mode }: OnMatchTypeModeDto,
```suggestion
    @MessageBody() [ type, mode ]: string[],
```

2021-09-30 15:04 UTC, ykoh42 commented on src/events/games/dto/on-match-type-mode.dto.ts
> +  readonly mode!: MatchGameMode;
class validator를 쓰면 400에러를 뿜어주는데 이러면 서버에러가 나버립니다. http exception 자체를 wsexception으로 돌리던지 해야해요.

2021-10-01 03:08 UTC, ykoh42 requested changes
우선 동작은 동작은 정상적으로 하는것 확인했습니다!

제가 잘못 테스트했 던 부분도 resolve 처리해놨어요

추가로 로비매니저인데 로비라는 단어가 사라졋다는 점과

변수명이 queue랑 set 이렇게 되어있어서 이해하는데 바로 직관적이진 않았던 점도 있었습니다.

2021-10-01 03:08 UTC, ykoh42 commented on src/events/games/dto/on-match-type-mode.dto.ts
> +  readonly mode!: MatchGameMode;
class validator 자체가 동작을 안해서 exception이 나오는지 확인을 못했습니다. class validator가 동작하게 만드는 방법을 모르겠어요 ㅠㅠ.. 동작안할이유가 없어보이는데 잘모르겠네요 인스턴스화가 안되어서 그런가..?

현재 코드에서는 class validator가 정상동작하지 않으니 존재할 이유가 없을 것같습니다. + 타입만 필요한 상황이라 클래스말고 인터페이스나 타입이 적절해보여요.

2021-10-01 03:08 UTC, ykoh42 commented on src/events/games/dto/on-match-type-mode.dto.ts
> +  readonly mode!: MatchGameMode;
```suggestion
export interface OnMatchTypeModeDto {
  readonly type!: MatchType;

  readonly mode!: MatchGameMode;
```

이런형태나

`{ type: string; mode: string }` 이런식의 타입도 괜찮을것같습니다.

2021-10-01 03:08 UTC, ykoh42 commented on src/events/events.gateway.ts
> +    @MessageBody() { type, mode }: OnMatchTypeModeDto,
제가 잘못테스트했습니다. 값이 잘 넘어와요!

2021-10-01 03:08 UTC, ykoh42 commented on src/events/events.gateway.ts
> +    @MessageBody() { type, mode }: OnMatchTypeModeDto,
제가 잘못테스트했습니다. 값이 잘 넘어와요!

2021-10-01 03:19 UTC, ykoh42 commented on src/events/games/lobby-manager.service.ts
> +  exhibition_hard: Set<Socket> = new Set<Socket>();
스네이크 케이스로 되어있는 부분도 수정이 필요할것같아요

2021-10-01 03:36 UTC, Jack-R-lantern commented on src/events/games/dto/on-match-type-mode.dto.ts
> +  readonly mode!: MatchGameMode;
제안해주신 인터페이스 형태로 변경했습니다.

2021-10-01 03:42 UTC, Jack-R-lantern commented on src/events/games/lobby-manager.service.ts
> +  exhibition_hard: Set<Socket> = new Set<Socket>();
스네이크케이스 부분은 수정했습니다. Map의 경우 더 고민해보고 결정하도록 하겠습니다.

2021-10-01 07:33 UTC, ykoh42 approved these changes
수정사항들확인했어용!

2021-10-01 07:37 UTC, merged