Feat 관전 가능방 가져오는 API 추가
404-DriverNotFound/backend-b pull request #90
Opened 2021-09-16 10:04 UTC by Jack-R-lantern

`GET` `/matches`  API 추가
Query { type: MatchType }
`GET` `/matches` -> `/matches/me` API로 변경

close #35

## 기능에 대한 설명

`GET` `/matches`
현재 관전 가능한 방의 리스트를 가져오는 API 추가
type으론 EXIBITION, LADDER

기존 자신의 대전 기록을 가져오는
`GET` `/matches`를 `GET` `/matches/me`로 변경

## ISSUE
close #35
해결한 이슈 번호를 기재해주세요.  
[feat] 이슈를 해결했을 경우 close #issue-number  
[fix] 이슈를 해결했을 경우 fix #issue-number

2021-09-16 12:55 UTC, ykoh42 requested changes
제가 생각하는 내용을 리뷰에 남겼습니다!

검토해봐주셨으면 해요!

2021-09-16 12:55 UTC, ykoh42 commented on src/matches/dto/get-spectate-filter.dto.ts
> +  @IsNotEmpty()
쿼리가 강제된다는 점이 애매한 것같습니다.

쿼리는 optional한 값이 되어야 맞는것같아요.

2021-09-16 12:55 UTC, ykoh42 commented on src/matches/matches.controller.ts
> +  @ApiOperation({ summary: '관전 가능한 모든 매치 정보를 가져옵니다.' })
`GET` `/matches` API가 API만 보면 모든 매치정보를 가져올 것같은데,

관전가능한 매치정보만 가져온다는점이 애매한것같아요.

`/matches/me` 처럼 쿼리를 통해 구분가능하게 한다던가 아니면

관전경기를 의미하는 endpoint로 이름을 짓는것이 맞을것같아요

2021-09-16 12:55 UTC, ykoh42 commented on src/matches/matches.controller.ts
> +    // TODO PAGINATION
PAGINATION이 channels 모듈에 예제가 많아서 추가해보셔도 좋을것같습니다!

2021-09-16 13:00 UTC, Jack-R-lantern commented on src/matches/matches.controller.ts
> +  @ApiOperation({ summary: '관전 가능한 모든 매치 정보를 가져옵니다.' })
이 부분은 그러면 `GET` `/matches/spectate`로 수정하겠습니다

2021-09-17 07:46 UTC, ykoh42 requested changes
리뷰 남겼습니다!

2021-09-17 07:46 UTC, ykoh42 commented on src/matches/matches.repository.ts
> +    qb.leftJoinAndSelect('match.loser', 'users4');
```suggestion
    qb.leftJoinAndSelect('match.user1', 'user1');
    qb.leftJoinAndSelect('match.user2', 'user2');
```

2021-09-17 07:46 UTC, ykoh42 commented on src/matches/matches.repository.ts
> +    qb.leftJoinAndSelect('match.loser', 'users4');
관전경기에서는 승자와 패자가 아직 결정되지 않아서 항상 null이라 정보가 필요없을것같아요

2021-09-17 07:46 UTC, ykoh42 commented on src/matches/matches.repository.ts
> +    if (type !== undefined) {
```suggestion
    if (type) {
```

2021-09-17 07:49 UTC, ykoh42 approved these changes

2021-09-17 07:50 UTC, merged